pipeline {
    agent any

    environment {
        DOCKER_USER = "mourad1966"
        KUBECONFIG_FILE = credentials('config')
        BUILD_TAG = "v${BUILD_ID}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo " ==> Clonage du dépôt GitHub (branche courante)"
                git(
                    branch: 'master',
                    url: 'https://github.com/mhadjeres1966/Jenkins_devops_exams.git',
                    credentialsId: 'github_creds'
                )
            }
        }

        stage('Build & Push Docker Images') {
            steps {
                script {
                    echo "  ==> Construction et push des images Docker"
                    def services = ['movie-service', 'cast-service']

                    //  Injection du token DockerHub ici
                    withCredentials([usernamePassword(credentialsId: 'github_creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS')]) {

                        for (svc in services) {
                            sh """
                                echo "==> Building image for ${svc}"
                                docker build -t $DOCKER_USER/${svc}:$BUILD_TAG ./${svc}
                                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                                docker push $DOCKER_USER/${svc}:$BUILD_TAG
                            """
                        }

                        sh "docker logout"
                    }
                }
            }
        }

        stage('Deploy to Dev & Staging') {
            steps {
                echo "  ==> Déploiement automatique sur dev et staging"
                sh '''
                    mkdir -p ~/.kube
                    cat $KUBECONFIG_FILE > ~/.kube/config
		    # J'ai changé les numéros de port car le pipeline me sortait une erreur port 30007 déjà utilisé
                    # Déploiement sur dev
                    helm upgrade --install jenkins-exam-dev ./charts \
                        --namespace dev --create-namespace \
                        --set movieService.image.repository=$DOCKER_USER/movie-service \
                        --set movieService.image.tag=$BUILD_TAG \
                        --set castService.image.repository=$DOCKER_USER/cast-service \
                        --set castService.image.tag=$BUILD_TAG \
		        --set service.nodePort=30007

                    # Déploiement sur staging
                    helm upgrade --install jenkins-exam-staging ./charts \
                        --namespace staging --create-namespace \
                        --set movieService.image.repository=$DOCKER_USER/movie-service \
                        --set movieService.image.tag=$BUILD_TAG \
                        --set castService.image.repository=$DOCKER_USER/cast-service \
                        --set castService.image.tag=$BUILD_TAG \
			--set service.nodePort=30008
                '''
            }
        }

	stage('Debug') {
	    steps {
		echo "GIT_BRANCH = ${env.GIT_BRANCH}"
	    }
        }

        stage('Approval & Deploy to Production') {
            when {
                expression { env.GIT_BRANCH == 'origin/master' || env.GIT_BRANCH == 'master' } // Passage au deploiemnt Seulement sur master
            }
            steps {
                script {
                    timeout(time: 20, unit: 'MINUTES') {
                        input message: "Souhaitez-vous déployer en production ?", ok: "Oui, déployer"
                    }

                    echo "  ==> Déploiement manuel en production approuvé"

                    sh '''
                        mkdir -p ~/.kube
                        cat $KUBECONFIG_FILE > ~/.kube/config

                        helm upgrade --install jenkins-exam-prod ./charts \
                            --namespace prod --create-namespace \
                            --set movieService.image.repository=$DOCKER_USER/movie-service \
                            --set movieService.image.tag=$BUILD_TAG \
                            --set castService.image.repository=$DOCKER_USER/cast-service \
                            --set castService.image.tag=$BUILD_TAG \
			    --set service.nodePort=30009
                    '''
                }
            }
        }
    }

    post {
        success {
            echo " ==> Pipeline terminé avec succès !"
        }
        failure {
            echo " ==> Échec du pipeline. Consultez les logs Jenkins."
        }
    }
}

